CREATE TABLE IF NOT EXISTS "Users" (
  id SERIAL PRIMARY KEY,
  username VARCHAR(60) UNIQUE NOT NULL,
  password_hash VARCHAR(60) NOT NULL
);

CREATE TABLE IF NOT EXISTS "PointResults" (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES "Users"(id) ON DELETE CASCADE,
  x REAL NOT NULL,
  y REAL NOT NULL,
  r REAL NOT NULL,
  is_hitted BOOLEAN NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);